import { CALL_TYPES } from '../callTypes';

/** 102.3 FM — LIMINAL. Loops, echoes, and the wrong timeline. */
export const LIMINAL_CALLS = [
  {
    id: 'liminal-the-loop',
    band: 1,
    callerId: '???-????',
    callerName: 'THE LOOP',
    signal: 3,
    type: CALL_TYPES.STAY_CALM,
    staticReward: 55,
    duration: 12,
    sanityPenalty: 20,
    lines: [
      '"I\'ve called before. I know I have. This feels familiar."',
      '"I\'ve called before. Something is different."',
      '"I\'ve called before. Did you change your voice?"',
      '"I\'ve called before. Haven\'t I? Are you even real?"',
      '"I\'ve called... haven\'t I called..."',
    ],
  },
  {
    id: 'liminal-347',
    band: 1,
    callerId: '3:47 AM',
    callerName: '3:47 AM',
    signal: 2,
    type: CALL_TYPES.DEAD_AIR,
    staticReward: 60,
    waitSeconds: 12,
    sanityDelta: -12,
    tape: 'Tape #3 — The 3:47 Sessions',
    lines: [
      '"It\'s 3:47 AM."',
      '...',
      'You check your clock.',
      '...',
      "It doesn't matter what it says.",
      '...',
      "It's 3:47 AM.",
      '...',
      "It's always 3:47 AM.",
      '...',
      'Just wait.',
    ],
  },
  {
    id: 'liminal-yesterday',
    band: 1,
    callerId: 'RECALLED',
    callerName: "YESTERDAY'S CALL",
    signal: 4,
    type: CALL_TYPES.RIGHT_ANSWER,
    staticReward: 65,
    lines: [
      '"We talked yesterday. For almost an hour."',
      '"You don\'t remember, do you."',
      '"You said you understood. You said you\'d help."',
      '"I need to know if you meant it."',
    ],
    choices: [
      {
        text: 'I remember. I meant it.',
        outcome:
          'Relief breaks in their voice. They describe the conversation. You recognize none of it. But it was clearly real.',
        sanityDelta: -15,
        staticMult: 2,
        tape: "Tape #4 — Yesterday's Frequency",
      },
      {
        text: "I don't remember you.",
        outcome: '"That\'s okay. That happens here." They hang up gently.',
        sanityDelta: -5,
        staticMult: 1,
      },
      {
        text: 'Who gave you this number?',
        outcome: '"You did. Yesterday." The line cuts.',
        sanityDelta: -10,
        staticMult: 1.5,
      },
    ],
  },
  {
    id: 'liminal-echo',
    band: 1,
    callerId: 'ECHO-ECHO',
    callerName: 'ECHO',
    signal: 3,
    type: CALL_TYPES.JUST_LISTEN,
    staticReward: 75,
    sanityDelta: -15,
    tape: 'Tape #5 — Echo Chamber',
    lines: [
      '"Can you hear me?"',
      'Can you hear me?',
      '"There\'s something wrong with my line."',
      'Something wrong with my line.',
      '"Every word I say comes back different."',
      'Comes back different.',
      '"Three days now."',
      'Three weeks now.',
      '"I\'m scared it\'ll match my real voice."',
      'Getting closer.',
      '...',
      "Don't be scared.",
      '...',
      'The echo goes quiet. So does the caller.',
    ],
  },
];
