import { CALL_TYPES } from '../callTypes';

/** 88.7 FM — LIVING. The banal made sinister. */
export const LIVING_CALLS = [
  {
    id: 'living-disconnected',
    band: 0,
    callerId: '1-800-███-████',
    callerName: 'NUMBER DISCONNECTED',
    signal: 3,
    type: CALL_TYPES.RIGHT_ANSWER,
    staticReward: 40,
    lines: [
      'A voice recites a phone number. Seven times. Exactly.',
      'On the eighth — silence.',
      '"That number. It belongs to you."',
      '"We\'ve been calling every night for three years."',
      '"Will you answer next time?"',
    ],
    choices: [
      {
        text: 'Yes.',
        outcome: 'The line goes cold. Something shifts permanently. They were waiting for that.',
        sanityDelta: -5,
        staticMult: 2,
      },
      {
        text: 'No.',
        outcome: 'Low laughter. Long. Then nothing.',
        sanityDelta: 0,
        staticMult: 1,
      },
      {
        text: 'Wrong number.',
        outcome: '"That\'s what they all say." Click. Something slides into your collection drawer.',
        sanityDelta: -3,
        staticMult: 1.5,
        tape: 'Tape #1 — The Wrong Number',
      },
    ],
  },
  {
    id: 'living-wrong-number',
    band: 0,
    callerId: 'UNKNOWN',
    callerName: 'WRONG NUMBER',
    signal: 4,
    type: CALL_TYPES.DEAD_AIR,
    staticReward: 25,
    waitSeconds: 8,
    lines: [
      'They called you.',
      'You answer.',
      '...',
      'Total silence. Eight seconds.',
      '...',
      '"Oh. Wrong number."',
      'Click.',
      '...',
      'The static sounded exactly like breathing.',
    ],
  },
  {
    id: 'living-collector',
    band: 0,
    callerId: 'PRIVATE',
    callerName: 'THE COLLECTOR',
    signal: 4,
    type: CALL_TYPES.RIGHT_ANSWER,
    staticReward: 45,
    lines: [
      '"Do you collect things?"',
      '"Most people do. They just don\'t know what."',
      '"I collect the last time someone says something."',
      '"The last time your grandfather said your name — I have it."',
      '"Would you like it back?"',
    ],
    choices: [
      {
        text: 'Yes.',
        outcome: 'She reads it back. Your body remembers it before your mind does.',
        sanityDelta: -10,
        staticMult: 1.5,
        tape: "Tape #2 — The Collector's Archive",
      },
      {
        text: 'No.',
        outcome: '"Smart. You can\'t unhear it." She hangs up gently.',
        sanityDelta: 0,
        staticMult: 1,
      },
      {
        text: 'How much?',
        outcome: '"It\'s not for sale. I just like knowing they\'re wanted." Warm laughter. Click.',
        sanityDelta: -5,
        staticMult: 2,
      },
    ],
  },
  {
    id: 'living-harold',
    band: 0,
    callerId: '555-0891',
    callerName: 'HAROLD',
    signal: 5,
    type: CALL_TYPES.JUST_LISTEN,
    staticReward: 30,
    sanityDelta: -8,
    lines: [
      '"Hello? Oh good. I love your station."',
      '"Got my garden in today. Tomatoes, mostly."',
      '"Ruth loves tomatoes. She\'ll be so pleased."',
      '...',
      '"...Ruth passed fourteen years ago this November."',
      '"I set her place at dinner again this morning."',
      '"Force of habit, I suppose."',
      '"...I suppose."',
      '"Well. Good night now."',
    ],
  },
];
