import { CALL_TYPES } from '../callTypes';

/** 117.8 AM — LOST. The dead, the missing, and the last thing they needed to say. */
export const LOST_CALLS = [
  {
    id: 'lost-guardian',
    band: 2,
    callerId: '6 MONTHS OLDER',
    callerName: 'GUARDIAN',
    signal: 1,
    type: CALL_TYPES.JUST_LISTEN,
    staticReward: 100,
    sanityDelta: 10,
    tape: 'Tape #6 — Signal From Guardian',
    lines: [
      "The signal comes in low. Like it's traveling a long way.",
      'A young man\'s voice. Easy. Someone who never took himself too seriously.',
      '"Yo. I know this is weird. Just listen, alright?"',
      '"I was brave. At the end. I need you to know that."',
      '"Tell my people I\'m good. That\'s all I needed to say."',
      '"I\'m watching over everybody. That\'s my thing now."',
      '"You know who this is for."',
      '"She\'s gonna be okay too. Tell her that."',
      '"Tell her she\'s not as lost as she thinks."',
      'He laughs. Quiet. Real.',
      '"Tell her I\'m still here. Just... different."',
      '...',
      'The signal holds three more seconds.',
      'Then warmth. Then static. Then nothing.',
    ],
  },
  {
    id: 'lost-missing-persons',
    band: 2,
    callerId: 'MOTHER',
    callerName: 'MISSING PERSONS',
    signal: 4,
    type: CALL_TYPES.RIGHT_ANSWER,
    staticReward: 90,
    lines: [
      '"My daughter\'s been gone three years."',
      '"This morning there was a cassette tape in my mailbox."',
      '"No postage. No return address. Just her name on the label."',
      '"Will you play it on air for me?"',
    ],
    choices: [
      {
        text: "Yes. I'll play it.",
        outcome:
          "It's her voice. She's okay. The silence after it ends is the quietest thing you've ever heard.",
        sanityDelta: -15,
        staticMult: 2,
        tape: 'Tape #7 — Found Signal',
      },
      {
        text: "Don't play it yet. Wait.",
        outcome:
          '"Wait for what?" You don\'t have a good answer. But something in you knows it\'s right.',
        sanityDelta: 0,
        staticMult: 1,
      },
      {
        text: 'Burn it.',
        outcome: '"...Yeah. Maybe." You stay on the line together. Neither of you speaks.',
        sanityDelta: 5,
        staticMult: 1.5,
      },
    ],
  },
  {
    id: 'lost-grand',
    band: 2,
    callerId: 'SHE CALLED',
    callerName: 'GRAND',
    signal: 1,
    type: CALL_TYPES.JUST_LISTEN,
    staticReward: 150,
    sanityDelta: 25,
    tape: 'Tape #8 — Her Voice',
    lines: [
      'The line crackles. Not interference. Distance.',
      "An elderly woman's voice. Strong. The kind that ran the whole house from one chair and knew everything before you said a word.",
      '"Baby. Don\'t fuss. I don\'t have long on this line."',
      '"It\'s exactly like I knew it would be."',
      '"They were all here when I arrived. Every last one of them. Lord, it was good to see their faces."',
      '"I want you to stop carrying guilt around like it\'s yours to keep. It never was."',
      '"You were always the one I watched closest."',
      '"Not because you worried me."',
      '"Because I could see what you were."',
      '"I still can."',
      '...',
      '"The strangest thing — I can hear you sometimes. Not always. But sometimes."',
      '"When it\'s real quiet."',
      '"Make it real quiet more often, you hear me?"',
      '...',
      '"I love you so much, baby. That didn\'t go anywhere."',
      'The static gets louder. Not frightening. Like warmth filling a room.',
      'Then silence.',
      '...',
      "You don't have to move for a while.",
      "That's okay.",
    ],
  },
  {
    id: 'lost-free-spirit',
    band: 2,
    callerId: 'THE WOODS',
    callerName: 'FREE SPIRIT',
    signal: 2,
    type: CALL_TYPES.JUST_LISTEN,
    staticReward: 120,
    sanityDelta: 20,
    tape: 'Tape #9 — Open Sky',
    lines: [
      'The signal sounds like open sky.',
      "A man's voice. Calm. Doesn't need to prove anything.",
      '"Hey there. Didn\'t think this was gonna work."',
      '"Ain\'t no big thing. That\'s what I keep thinking. It just... ain\'t."',
      '"It was easier than you\'d think. That\'s the God\'s honest truth."',
      '"The deer out here — you wouldn\'t believe. Big ones. Not scared of anything."',
      '"I think I\'ve seen every bird I ever wanted to see."',
      '"You take care of yourself. Look out for the ones you love."',
      '"Go outside more."',
      'He laughs.',
      'The signal fades slowly.',
      'Like a sunset.',
    ],
  },
];
