import { CALL_TYPES } from '../callTypes';

/** ???.? — ████████. The frequency itself. */
export const UNKNOWN_CALLS = [
  {
    id: 'unknown-origin',
    band: 4,
    callerId: 'APR 14, 1923',
    callerName: 'ORIGIN',
    signal: 1,
    type: CALL_TYPES.JUST_LISTEN,
    staticReward: 300,
    sanityDelta: -30,
    tape: 'Tape #13 — First Transmission',
    lines: [
      'Enormous static. Ancient.',
      'A voice. Male. 1920s diction. Formal and amazed.',
      '"Hello? Is anyone out there? This is the first test of the —"',
      'Crackle. Warp.',
      '"— frequency. If you can hear this, it worked."',
      '"It worked across more than we planned."',
      '...',
      '"I can\'t see you. But I know someone is there."',
      '"I can feel it."',
      '...',
      'He says your name.',
      'Not your username.',
      'Your name.',
      '...',
      'The signal goes quiet for one hundred years.',
    ],
  },
  {
    id: 'unknown-you-called-us',
    band: 4,
    callerId: 'YOUR OWN NUMBER',
    callerName: 'YOU CALLED US',
    signal: 3,
    type: CALL_TYPES.RIGHT_ANSWER,
    staticReward: 280,
    lines: [
      '"We want to remind you of something."',
      '"You found this frequency. You tuned here."',
      '"You answered every call. None of this was done to you."',
      '"Why did you choose this?"',
    ],
    choices: [
      {
        text: 'I wanted to hear them.',
        outcome: 'The frequency hums in approval. All your tapes glow briefly.',
        sanityDelta: 15,
        staticMult: 3,
      },
      {
        text: 'I was looking for someone.',
        outcome: '"We know." Then warmth. Actual warmth through the speakers.',
        sanityDelta: 20,
        staticMult: 2,
        tape: 'Tape #14 — The Choice',
      },
      {
        text: "I don't know why.",
        outcome:
          '"That\'s the most complete answer." Everything goes quiet in a way that feels earned.',
        sanityDelta: 10,
        staticMult: 2,
      },
    ],
  },
  {
    id: 'unknown-dead-air',
    band: 4,
    callerId: '— — — — —',
    callerName: 'DEAD AIR',
    signal: 0,
    type: CALL_TYPES.DEAD_AIR,
    staticReward: 500,
    waitSeconds: 20,
    sanityDelta: 30,
    tape: 'Tape #15 — What Answered',
    lines: [
      'The station goes dark.',
      'Every monitor.',
      'Every light.',
      "The amber glow that's been your constant —",
      'Gone.',
      '...',
      'Just you.',
      'In the dark.',
      '...',
      'Wait.',
      '...',
      'Something answers.',
      '...',
      'The game will never tell you what it was.',
      '...',
      'But you felt it.',
    ],
  },
];
